liveness:
  path: /health/liveness
  controller: Browncat\HealthCheckBundle\Controller\HealthCheckController::checkLiveness
readiness:
  path: /health/readiness
  controller: Browncat\HealthCheckBundle\Controller\HealthCheckController::checkReadiness
startup:
  path: /health/startup
  controller: Browncat\HealthCheckBundle\Controller\HealthCheckController::checkStartup
healthz:
  path: /healthz
  controller: Browncat\HealthCheckBundle\Controller\HealthCheckController::healthOverview