services:
  # Register checks
  Browncat\HealthCheckBundle\Check\DoctrineConnectionHealthCheck:
    public: false
    arguments: ["@?doctrine"]
    tags: ['health_check.check']

  # Register checkers
  Browncat\HealthCheckBundle\Service\GlobalHealthChecker:
    public: false
    tags: ['health_check.checker']

  health_check.checker.global:
    alias: Browncat\HealthCheckBundle\Service\GlobalHealthChecker
    public: true

  Browncat\HealthCheckBundle\Service\LivenessChecker:
    public: false
    tags: ['health_check.checker']

  health_check.checker.liveness:
    alias: Browncat\HealthCheckBundle\Service\LivenessChecker
    public: true

  Browncat\HealthCheckBundle\Service\ReadinessChecker:
    public: false
    tags: ['health_check.checker']

  health_check.checker.readiness:
    alias: Browncat\HealthCheckBundle\Service\ReadinessChecker
    public: true

  Browncat\HealthCheckBundle\Service\StartupChecker:
    public: false
    tags: ['health_check.checker']

  health_check.checker.startup:
    alias: Browncat\HealthCheckBundle\Service\StartupChecker
    public: true

  # Configure controller
  Browncat\HealthCheckBundle\Controller\HealthCheckController:
      arguments: ['@logger']
      tags: ['controller.service_arguments']
